config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  resources :recipes do
    collection do
      get :search
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  scope :three_most_liked, -> { order(likes: :desc).first(3) }
  scope :search, -> (search) { where 'name LIKE ?', "%#{search}%" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  prepend_view_path Rails.root.join('frontend')
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @recipes = Recipe.three_most_liked
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def search
    @recipes = Recipe.search(params[:search])
  end

  def show
    @recipe = Recipe.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Recipes
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all'
  %body
    = yield
    = javascript_pack_tag 'application'

app/views/pages/home.html.haml
%h1 Recipes
= form_tag(search_recipes_path, method: :get, id: 'search_recipe') do
  = text_field_tag :search
  = submit_tag 'search'
- @recipes.each do |recipe|
  = link_to recipe_path(recipe) do
    = recipe.name

app/views/recipes/search.html.haml
- @recipes.each do |recipe|
  = link_to recipe_path(recipe) do
    = recipe.name

app/views/recipes/show.html.haml
= @recipe.name
= @recipe.description